import React from 'react';

const ShifaRahTerms = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white">
      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-xl font-bold text-gray-800 mb-2">
        Shifa Nour : TERMS AND CONDITIONS
        </h1>
        
      </div>

      {/* Content */}
      <div className="space-y-6 text-gray-700 leading-relaxed">
      <p className="text-lg text-gray-600">Welcome to Shifa Nour!</p>
        <p>
          The portals www.Shifa Nour.com ("Shifa Nour") and the corresponding mobile application (collectively, "Platforms"), are managed and operated by Reliance Retail Limited ("Reliance", "we", "us" or "our"). Any natural or legal person who accesses and/or uses the Platforms in any manner ("you" or "your") or uses any current or future service or functionality or offer made available on the Platforms ("Service") will be subject to these terms and conditions for use of the Platforms ("Terms"), as updated from time to time. Your access to Services, other platforms or utilisation of Products (defined below), offers or promotions in relation to the Products, as may be provided by us or our affiliates, may be governed by other terms and conditions, policies or guidelines ("Additional Terms") along with these Terms. If these Terms are inconsistent with such Additional Terms, the Additional Terms will control to the extent of such inconsistency with respect to the applicable Service or utilisation of the Product.
        </p>

        <p>
          These Terms constitute an electronic record within the meaning of the Information Technology Act, 2002. This electronic record is generated by a computer system and does not require any physical or digital signatures. Please read these Terms carefully before using or accessing the Platforms or availing any Service. By using the Platforms or availing any Service, you signify your agreement to be bound by these Terms.
        </p>

        <p>
          For the purposes of these Terms, "Products" shall mean the diverse range of fashion, home and beauty products listed on the Platforms from time to time and other products offered for sale to you on both the Platforms; and (c) We and you are hereinafter individually referred to as "Party" and collectively as "Parties".
        </p>

        <p>
          These Terms are divided into 2 (two) parts. Please carefully read all the parts to understand the conditions applicable for usage of the Platforms and for the purchase of Products thereof.
        </p>

        {/* Section 1: GENERAL */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">1. GENERAL</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                The terms and conditions for usage of the Platforms as set out herein ("Terms of Use") specifically govern your access and use of the Platforms, which provides a forum for you to inter alia discover, select and buy Products listed on the Platforms at the indicated price at any time, from the locations serviceable by us.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                Please note that we may from time to time, modify the Terms of Use that govern your use of the Platforms. Every time you wish to use our Platforms, please check these Terms of Use to ensure that you understand the terms and conditions that apply at that time. Further, please note that we reserve the right to either change the format and the content of the Platforms or suspend the operation of the Platforms for support or maintenance work, in order to update the content or for any other reason, at any time.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                The accessing, browsing, or otherwise using the Platforms indicates your agreement to these Terms of Use, the Privacy Policy and any other policies or guidelines that may be applicable to the Platforms at the time of your access and usage of the Platforms and which may be updated from time to time (collectively, the "Agreement").
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                We authorise you to view and access the Platforms solely for identifying Products, carrying out purchases of Products and processing returns and refunds, in accordance with the Return and Refund Policy. We therefore grant you a limited, revocable permission to access and use the Services.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                By accepting this Agreement, you affirm that you are 18 (Eighteen) years of age or above and are fully competent to enter into this Agreement, and to abide by and comply with this Agreement. If a user is below 18 (Eighteen) years of age, it is assumed that he/she is using/browsing the concerned Platform under the supervision of his/her parent or legal guardian and that such user's parent or legal guardian has read and agrees to the terms of this Agreement, including the terms of purchase of Products on behalf of the minor user. In the event we are made aware that a user is under the age of 18 and is using/browsing the Platform without the supervision of his/her parent or legal guardian, we reserve the right to deactivate such user's account without further notice. Further, if you are using the Services on behalf of a company or organisation, you represent that you have the authority to act on behalf of that entity, and that such entity accepts this Agreement.
              </p>
            </div>
          </div>
        </section>

        {/* Section 2: REGISTRATION */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">2. REGISTRATION OF YOUR ACCOUNT</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <div>
                <p className="mb-2">
                  In order to purchase Products on the Platforms and/or avail Services thereof, you will have to register on the Platform. Registration is a one-time process and is free of cost.
                </p>
                <p className="mb-2">You may register on Shifa Nour in one of the following ways:</p>
                <div className="ml-4 space-y-2">
                  <div className="flex items-start space-x-2">
                    <span className="text-sm">a.</span>
                    <p>Creating an Shifa Nour account: by providing the relevant information for the creation of your account on Shifa Rah and after filling in the necessary forms and providing the necessary details as may be required by us at the time of your registration. Following this, an account will be created by Reliance for you.</p>
                  </div>
                  <div className="flex items-start space-x-2">
                    <span className="text-sm">b.</span>
                    <p>Using a third-party account: you may use the login credentials of the account maintained by you with a Reliance-integrated third-party (illustratively, Google or Facebook), in which case you will also be subject to the relevant third-party terms and conditions applicable to such account.</p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You are solely authorized to operate the account created by you. Consequently, it is your responsibility to maintain the confidentiality of the log in credentials of your account on the Platforms and for restricting access to your computer/mobile/other similar devices to prevent unauthorized access to your account. You shall remain solely liable for all the actions undertaken through your account.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You will: (a) immediately inform us of any unauthorized use of the account or any other security breach; and (b) ensure that you log out of your account at the end of each session. We, our employees, agents, directors and officers will not be liable for any loss or direct or indirect damage arising from your failure to comply with these Terms of Use. You may be held liable for any losses incurred to us or any other user due to unauthorized use of their account by you. We reserve the right to refuse access to the Platform(s), terminate accounts, remove or edit content at any time without notice to you.
              </p>
            </div>
          </div>
        </section>

        {/* Section 3: COMMUNICATION */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">3. COMMUNICATION AND UNSUBSCRIPTION</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                By accepting the Terms of Use, you also accept to receive news, updates, offers/ campaign related SMS, to the mobile phone number provided by you. By accessing and using the Platforms and/or verifying your contact number with us, you explicitly consent to receive such communications (through call, SMS, email or other digital and electronic means) from us and/or our authorized representatives regarding any new services or offerings, even if your contact number is registered under the DND/NCPR list under the Telecom Commercial Communications Customer Preference Regulations, 2018.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You can unsubscribe/ opt-out from receiving marketing/ promotional communications, newsletters and other notifications from us at any time by following the instructions set out in such communications.
              </p>
            </div>
          </div>
        </section>

        {/* Continue with remaining sections... */}
        {/* Section 4: ACCESS TO IMAGES */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">4. ACCESS TO IMAGES</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                By accepting the Terms, you provide explicit consent to us, to have access to your camera and gallery applications installed in your phone or computer, through which you are using the Platforms, for the purpose of enabling us to provide Services.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You acknowledge and agree that in addition to the restrictions set out in paragraph 11 (User Warranties and Restrictions), you will ensure that any image uploaded by you: (i) does not belong to another person, in relation to which you do not have any right; or (ii) such image is not defamatory, obscene, pornographic, paedophilic, invasive of another's privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethically objectionable; or (iii) is not harmful to child; (iv) should not infringe any copyright or other proprietary rights; (v) does not impersonate another person; or (vi) does not contain software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource; or (vii) should not contain indecent representation of women in any form; or (viii) violates any law for the time being in force, including but not limited to Information Technology Act, 2000, Indecent Representation of Women (Prohibition) Act, 1986 and Indian Penal Code 1860, and the rules made thereunder (as applicable).
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                When you upload images that are covered by third party intellectual property rights, you grant or in case of a third party, ensure that they are granted by you (whether by yourself or on behalf of the third party), a non-exclusive, royalty-free, transferable, sub-licensable, worldwide licence to use, distribute, copy, or display, translate and create derivative works of the images that you upload, solely in connection with the Services.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You acknowledge and accept that for the purpose of providing Services, the images uploaded by you may be accessed, used or processed by a third party, and that we have no liability, obligation or responsibility of any nature towards you or such third party and the contract under such instances remains between you and such third party.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                In the event of breach of any of the obligations mentioned in this paragraph 4 (Access to Images), you accept that we will not be liable to you or any third-party in relation to any claims, losses, liabilities, damages, and/or costs (including any attorney fees and costs) which may arise from breach of the aforesaid obligations. You further agree that you will be liable to indemnify us in accordance with paragraph 12 (Indemnification and Limitation of Liability) of the Terms.
              </p>
            </div>
          </div>
        </section>

        {/* Section 5: DISCLAIMER OF WARRANTIES */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">5. DISCLAIMER OF WARRANTIES, INACCURACIES OR ERRORS</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                We will try to ensure that all information and recommendations, whether in relation to the Products, Services, offerings or otherwise (hereinafter "Information") provided as part of the Platforms is correct at the time of inclusion on the concerned Platform. We do not guarantee the accuracy of the Information. We make no representations or warranties as to the completeness or accuracy of Information.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You agree that Information is being supplied to you on the condition that you will make your own determination as to the suitability of such information for your purpose prior to use or in connection with the making of any decision. No Information on the Platforms shall constitute an invitation to invest in us or any affiliates. Any use of the Platforms or the Information is at your own risk. Neither we, our affiliates, nor their officers, employees or agents shall be liable for any loss, damage or expense arising out of any access to, use of, or reliance upon, this website, the Information, or any third-party website linked to the Platforms.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                As a means to assist the users in identifying the Products of their choice, we provide visual representations on the Platforms including graphics, illustrations, photographs, images, videos, charts, screenshots, infographics and other visual aids. While reasonable efforts are made to provide accurate visual representation, we disclaim any guarantee or warranty of exactness of such visual representation or description of the Product, with the actual Product ultimately delivered to users.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                THE PLATFORMS AND THE SERVICES ARE PROVIDED TO YOU ON AN "AS IS" AND "WHERE-IS" BASIS, WITHOUT ANY REPRESENTATIONS OR WARRANTIES. WE, FOR OURSELF AND ANY THIRD-PARTY PROVIDING MATERIALS, SERVICES, OR CONTENT TO THIS WEBSITE, MAKE NO REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT OF THIRD-PARTY RIGHTS.
              </p>
            </div>
          </div>
        </section>

        {/* Section 6: AVAILABILITY AND ACCESSIBILITY */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">6. AVAILABILITY AND ACCESSIBILITY OF THE PLATFORMS</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                We control and operate the Platforms from India and make no representation that the materials and the content available on the Platforms is appropriate to be used or will be available for use in other locations outside India. If you use the Platforms from outside India, you are entirely responsible for compliance with all applicable local laws.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                We constantly monitor the user's account in order to avoid fraudulent accounts and transactions. Users with more than one account or availing referral vouchers fraudulently shall be liable for legal actions under law and we reserve the right to recover the cost of goods, collection charges and lawyer fees from persons using the Platforms fraudulently.
              </p>
            </div>
          </div>
        </section>

        {/* Section 7: THIRD PARTY INTERACTION */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">7. THIRD PARTY INTERACTION AND LINKS TO THIRD PARTY SITES</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                In your use of the Platforms, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of advertisers or members or sponsors of the Platforms or access any other third-party website linked to the Platforms. You agree that we have no liability, obligation or responsibility for any such correspondence, purchase or promotion.
              </p>
            </div>
          </div>
        </section>

        {/* Section 8: COPYRIGHTS */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">8. COPYRIGHTS IN RELIANCE CONTENT</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                The Platforms contain material, including text, graphics and sound, which is protected by copyright and/or other intellectual property rights ("Reliance Content"). All copyright and other intellectual property rights in the Reliance Content are either owned by us or have been licensed to us by the owner(s) of those rights.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You may use and display the Reliance Content on your personal computer only for your personal use subject to the grant of a limited, revocable, personal, non-exclusive and non-transferable license to you by us when you register on any of the Platforms.
              </p>
            </div>
          </div>
        </section>

        {/* Section 9: TRADEMARKS */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">9. TRADEMARKS</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                All the trade names associated with us and all Products and logos denoted with TM are trademarks or registered trademarks of us or our affiliates. Our trademarks may not be used in connection with any product or service that is not our product or service.
              </p>
            </div>
          </div>
        </section>

        {/* Section 10: LICENSE AND USE */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">10. LICENSE AND USE OF YOUR CONTENT</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You grant to us a royalty-free, perpetual, irrevocable, non-exclusive right and license to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on any material posted by you on the Platforms without additional approval or consideration.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                We reserve the right to terminate access to the Platforms at any time and without notice. Further this limited license terminates automatically, without notice to you, if you breach any of these Terms of Use.
              </p>
            </div>
          </div>
        </section>

        {/* Section 11: USER WARRANTIES */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">11. USER WARRANTIES AND RESTRICTIONS</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You represent and warrant that: (a) your use of the Platforms and/or Services will not violate any applicable law or regulation; (b) all information that is submitted to us in connection with the Platforms and/or Services is true, accurate and lawful; (c) use of the content and material you supply does not breach any applicable Agreement and will not cause injury to any person or entity.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You will use the Platforms for lawful purposes only and will not undertake any activity that is harmful to the Platforms or its content or otherwise not envisaged through the Platforms.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You are prohibited from hosting, displaying, uploading, modifying, publishing, transmitting, storing, updating or sharing on or through the Platforms, any information that: belongs to another person and to which you do not have any right; is harmful to minors in any way; infringes any patent, trademark, copyright or other proprietary rights; violates any law for the time being in force; or threatens the unity, integrity, defence, security or sovereignty of India.
              </p>
            </div>
          </div>
        </section>

        {/* Section 12: INDEMNIFICATION */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">12. INDEMNIFICATION AND LIMITATION OF LIABILITY</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                You agree to indemnify, defend and hold harmless us, our affiliates, officers, directors, employees, consultants, licensors, agents, and representatives from and against any and all third-party claims, losses, liabilities, damages, and/or costs arising from your access to or use of the Platforms or the Services, violation of these Terms of Use, or infringement of any intellectual property or other rights.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                To the fullest extent permitted by law, in no event shall Reliance or any of its directors, officers, employees, agents be liable to you for any direct, indirect, special, incidental, consequential, exemplary, or punitive damage arising from, or directly or indirectly related to, the use of, or the inability to use, the Platforms or the Services.
              </p>
            </div>
          </div>
        </section>

        {/* Section 13: ACCESS OUTSIDE INDIA */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">13. ACCESS OUTSIDE THE REPUBLIC OF INDIA</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                Reliance makes no representation that the content on the Platforms is appropriate to be used or accessed outside the Republic of India. Your use of or access to the Platforms from outside the Republic of India is at your own risk and you are responsible for compliance with the laws of such jurisdiction.
              </p>
            </div>
          </div>
        </section>

        {/* Section 14: APPLICABLE LAW */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">14. APPLICABLE LAW AND JURISDICTION</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                These Terms of Use are governed by and to be interpreted in accordance with laws of India, without regard to the choice or conflicts of law provisions of any jurisdiction. You agree, in the event of any dispute arising in relation to these Terms of Use or any dispute arising in relation to the Platforms, to submit to the jurisdiction of the courts located at Mumbai, India.
              </p>
            </div>
          </div>
        </section>

        {/* Section 15: GRIEVANCE OFFICER */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">15. GRIEVANCE OFFICER</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                In accordance with the applicable law, any grievances which you may have with respect to the information shared by you with us hereunder and its treatment or any grievance related to Services being availed hereunder, may be directed to:
              </p>
            </div>
            <div className="ml-6 space-y-2">
              <p><strong>Name:</strong> Anirban Chatterjee</p>
              <p><strong>Designation:</strong> Grievance Officer</p>
              <p><strong>Email Address:</strong> grievance.officer@ajio.com</p>
            </div>
          </div>
        </section>

        {/* Section 16-20: ADDITIONAL TERMS */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">16. FORCE MAJEURE</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                We will not be held responsible for any delay or failure to comply with its obligations if the delay or failure arises from any cause which is beyond our reasonable control.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">17. WAIVER</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                No provision in these Terms of Use will be deemed waived and no breach excused, unless such waiver or consent is in writing and signed by us.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">18. SEVERABILITY</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                If any provision of these Terms of Use is held by a court of competent jurisdiction to be unenforceable under applicable law, then such provision will be excluded from these Terms of Use and the remainder will be interpreted as if such provision were so excluded.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">19. AMENDMENT</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                These Terms of Use are subject to amendments and modifications and may be updated from time to time, without any advance notice. You are requested to regularly review the Terms of Use as available on the Platforms.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">20. MISCELLANEOUS</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                In addition to these Terms of Use, you will also ensure that you are in compliance with the terms and conditions of the third parties, such as bank offers terms and conditions, brand promotional offers, whose links, if any, are contained/embedded in the Services.
              </p>
            </div>

            <div className="flex items-start space-x-3">
              <div className="w-1 h-1 bg-gray-500 rounded-full mt-2 flex-shrink-0"></div>
              <p>
                These Terms of Use supersede all previous oral and written terms and conditions (if any) communicated to you by us, for the use of the Platforms, and the rights and liabilities with respect to any Services to be provided by us shall be limited to the scope of these Terms of Use.
              </p>
            </div>
          </div>
        </section>

        {/* Customer Care Section */}
        <section className="mt-8">
          <h2 className="text-sm font-semibold text-gray-800 mb-2">CUSTOMER CARE</h2>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="bg-gray-100 p-6 rounded-lg">
              <div>
                <p className="mb-2"><strong>Mr. Sunil Kumar</strong></p>
                <p className="mb-2">Landmark Online India Pvt Ltd</p>
                <p className="mb-2">77° Town Centre, Building No. 3, West Wing,Off HAL Airport Road, Yamlur P.O.,Bangalore - 560 037, Karnataka, India</p>
                <p className="mb-2"><strong>Phone:</strong> 080-41796565 (Extn: 5228)</p>
                <p className="mb-2"><strong>Email:</strong> SunilKumar.J@landmarkgroup.in</p>
                <p className="mb-2"><strong>Time:</strong> Mon – Sat (9:00 - 17:00)</p>
              </div>
              </div>
            </div>
          </div>
          
          <div className="mt-6">
            <p className="text-center text-gray-600">
              Thank you for your cooperation. We hope you find this Website helpful and convenient to use.
            </p>
          </div>
        </section>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-gray-200">
          <div className="text-center text-sm text-gray-500">
            <p>© 2025 Shifa Nour. All rights reserved.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ShifaRahTerms;